.github/workflows/aot-test.yml
After compiling the AOT binaries for testing in a PR CI run, upload them as artifacts. This will make it more convenient for people to experiment with AOT compilation without setting up a toolchain locally.
=> Upload the AOT binaries in test CI

build.sbt
The warning is caused by no logging provider being specified for slf4j. Added simple provider for now - seems like a better decision than just using nop explicitely, although explicit nop makes the warning disappear as well.
Issue: #26
=> Add simple logging provider to get rid of warnings

build.sbt
Issue: #28 
On Linux x86_64, this reduces the binary size from 68.65MB to **44.43 MB**. I'd say a 1/3 saving is worth it.
=> Optimize release AOT builds for size

build.sbt
Issue: #36 
Works for my copy of Graal 24.
@Karolina-Bogacka could you verify this on yours?
=> Get rid of unsafe access warnings on JDK 24

build.sbt, src/main/scala/eu/neverblink/jelly/cli/command/rdf/RdfToJelly.scala, src/test/scala/eu/neverblink/jelly/cli/command/rdf/RdfToJellySpec.scala
Issue: #55
Add an option that allows for emitting non-delimited Jelly data.
=> rdf to-jelly: add --delimited option

build.sbt, src/main/scala/eu/neverblink/jelly/cli/JellyCommand.scala, src/main/scala/eu/neverblink/jelly/cli/command/rdf/RdfFormat.scala, src/main/scala/eu/neverblink/jelly/cli/command/rdf/RdfToJelly.scala, src/test/scala/eu/neverblink/jelly/cli/command/helpers/DataGenHelper.scala, src/test/scala/eu/neverblink/jelly/cli/command/helpers/TestFixtureHelper.scala, src/test/scala/eu/neverblink/jelly/cli/command/rdf/RdfFromJellySpec.scala, src/test/scala/eu/neverblink/jelly/cli/command/rdf/RdfToJellySpec.scala
Issue: #56
Also added the shared `--quiet` option to silence warnings on stderrrrrrrr.
=> rdf to-jelly: add converting from Jelly text format

.github/workflows/aot-publish.yml, .github/workflows/aot-test.yml, build.sbt
Also, tidy up the part of build.sbt that works out the options to pass on to Graal.
I initially wanted to use this occasion to enable COH in Graal, but it seems they were faster than me, they are already way ahead of everyone with 4-byte headers: https://www.graalvm.org/jdk24/reference-manual/native-image/optimizations-and-performance/ObjectHeaderSize/
Nice.
=> Upgrade Graal to 24 for AOT builds

build.sbt
Stable release in preparation for releasing jelly-cli.
=> Update Jelly-JVM to 2.10.0

README.md, build.sbt, src/main/scala/eu/neverblink/jelly/cli/command/rdf/RdfInspect.scala
=> Add examples to readme

README.md, build.sbt, src/main/scala/eu/neverblink/jelly/cli/App.scala, src/main/scala/eu/neverblink/jelly/cli/Exceptions.scala, src/main/scala/eu/neverblink/jelly/cli/command/rdf/RdfFromJelly.scala, src/main/scala/eu/neverblink/jelly/cli/command/rdf/RdfSerDesCommand.scala, src/main/scala/eu/neverblink/jelly/cli/command/rdf/RdfToJelly.scala, src/main/scala/eu/neverblink/jelly/cli/command/rdf/RdfTranscode.scala, src/test/scala/eu/neverblink/jelly/cli/command/rdf/RdfTranscodeSpec.scala
It lets you turn one or more input Jelly files into a single output stream, very, very fast.
There are some TODOs left, for future functionalities. I will open an issue to implement them.
I renamed `RdfTranscodeCommand` to `RdfSerDesCommand` to avoid confusion. Transcoding is something that was already in Jelly-JVM and had this specific meaning I use in this PR (jelly-to-jelly).
=> Implement the rdf transcode command

src/main/scala/eu/neverblink/jelly/cli/command/rdf/RdfFromJelly.scala, src/main/scala/eu/neverblink/jelly/cli/command/rdf/RdfValidate.scala, src/main/scala/eu/neverblink/jelly/cli/util/args/IndexRange.scala, src/test/scala/eu/neverblink/jelly/cli/command/rdf/RdfFromJellySpec.scala
Closes: #57
Also expanded on the tests a little bit. Seems to work.
Will make it easier to later implement #4 – left a note where to do it
=> rdf from-jelly: add --take-frames argument

src/main/scala/eu/neverblink/jelly/cli/command/rdf/RdfValidate.scala, src/test/scala/eu/neverblink/jelly/cli/command/rdf/RdfValidateSpec.scala
=> rdf validate: add checks for version <= 0

build.sbt, src/test/scala/eu/neverblink/jelly/cli/command/rdf/RdfToJellySpec.scala
=> rdf to-jelly: make sure name table has size >=8

src/main/scala/eu/neverblink/jelly/cli/App.scala, src/main/scala/eu/neverblink/jelly/cli/JellyCommand.scala, src/main/scala/eu/neverblink/jelly/cli/util/jena/riot/CliRiot.scala, src/main/scala/eu/neverblink/jelly/cli/util/jena/riot/LangNQuadsGeneralized.scala, src/main/scala/eu/neverblink/jelly/cli/util/jena/riot/LangNTriplesGeneralized.scala, src/main/scala/eu/neverblink/jelly/cli/util/jena/riot/LangNTupleGeneralized.scala, src/test/resources/generalized.nq, src/test/resources/generalized.nt, src/test/scala/eu/neverblink/jelly/cli/command/helpers/TestFixtureHelper.scala, src/test/scala/eu/neverblink/jelly/cli/command/rdf/RdfToJellySpec.scala
Resolves: #88 
We basically spin our own versions of NT and NQ parsers that can ingest generalized RDF, and then we re-register them in Jena as the only NT/NQ parsers.
I don't think there is an easier way to achieve this. The checks disallowing generalized RDF are hardcoded into the parsers.
=> rdf to-jelly: support generalized RDF input

src/main/scala/eu/neverblink/jelly/cli/command/rdf/RdfToJelly.scala, src/main/scala/eu/neverblink/jelly/cli/command/rdf/util/RdfJellySerializationOptions.scala, src/main/scala/eu/neverblink/jelly/cli/util/jena/riot/JellyStreamWriterGraphs.scala, src/test/scala/eu/neverblink/jelly/cli/command/helpers/DataGenHelper.scala, src/test/scala/eu/neverblink/jelly/cli/command/rdf/RdfToJellySpec.scala
=> rdf to-jelly: implement the GRAPHS stream type

src/main/scala/eu/neverblink/jelly/cli/util/jena/StatementUtils.scala, src/test/scala/eu/neverblink/jelly/cli/command/rdf/RdfValidateSpec.scala
Closes: #107
This was not allowed by mistake. I've added a regression test for this.
=> rdf validate: allow quoted triples in S position

src/main/scala/eu/neverblink/jelly/cli/util/jena/OrderedRdfCompare.scala, src/test/scala/eu/neverblink/jelly/cli/command/helpers/TestFixtureHelper.scala, src/test/scala/eu/neverblink/jelly/cli/command/rdf/RdfValidateSpec.scala, src/test/scala/eu/neverblink/jelly/cli/util/jena/RdfCompareSpec.scala
Closes #113
Added a regression test for that. Also improved the error messages emitted by the validator to point to the exact RDF term that's not matching.
=> rdf validate: fix comparing bnodes in quoted triples

src/main/scala/eu/neverblink/jelly/cli/command/rdf/RdfToJelly.scala, src/test/scala/eu/neverblink/jelly/cli/command/rdf/RdfToJellySpec.scala
Issue: #115 
For now, I have decided not to emit a warning when the logical type is set to something complex like GRAPHS, that expects framing, and the physical type is basically continuous, since the user can solve this through manipulating frame size. Let me know if you expect something different.
=> Fix the problem of logical type not propagating properly

src/main/scala/eu/neverblink/jelly/cli/command/rdf/RdfValidate.scala, src/test/scala/eu/neverblink/jelly/cli/command/rdf/RdfValidateSpec.scala
=> rdf validate: fix comparisons with empty frames

build.sbt, src/test/scala/eu/neverblink/jelly/cli/command/rdf/RdfToJellySpec.scala
This required fixing one test that was expecting buggy behavior that was fixed in 3.1.1.
=> Update Jelly-JVM to 3.1.1

src/main/scala/eu/neverblink/jelly/cli/command/rdf/RdfFromJelly.scala, src/main/scala/eu/neverblink/jelly/cli/command/rdf/util/RdfFormat.scala, src/main/scala/eu/neverblink/jelly/cli/util/jena/StreamRdfBatchSink.scala, src/main/scala/eu/neverblink/jelly/cli/util/jena/StreamRdfBatchWriter.scala, src/test/scala/eu/neverblink/jelly/cli/command/helpers/DataGenHelper.scala, src/test/scala/eu/neverblink/jelly/cli/command/rdf/RdfFromJellySpec.scala
Closes #93 
I add `StreamRdfBatchSink` which implements `StreamRDF`. The class builds a Jena Model while receiving events, and when finishing, serializes the model into a selected format and streams it out. This is plugged into the `from-jelly` command with a new format `RdfFormat.Jena.BatchWriteable`, and by moving the writer initialization out of `jellyToLang` to the call-sites. I add tests for checking graph isomorphism for both rdfxml and jsonld, and remove the test for the non-streaming format error, as there are no longer any non-writeable formats defined.
=> GH-93 Allow non streaming output formats in rdf from-jelly

README.md
Issue https://github.com/Jelly-RDF/setup-cli/issues/3
=> Document the existence of jelly-cli/setup-cli GitHub action

.github/workflows/aot-test.yml, build.sbt, graal.json
=> Add GraalVM reflection configuration for JSON serializer needed for JSONLD

src/main/scala/eu/neverblink/jelly/cli/command/rdf/RdfInspect.scala, src/main/scala/eu/neverblink/jelly/cli/command/rdf/util/MetricsPrinter.scala, src/test/scala/eu/neverblink/jelly/cli/command/rdf/RdfInspectSpec.scala
Closes #74 
Everything came together really nicely with context parameters.
One thing is that I'm not sure how accurate the statistics are. I use getSerializedSize() of ProtoMessage as the source (and length of encoded string + 1 for the tag byte), but I'm not sure if these are correct. 
I was hoping that triples_size would equal subject_size + predicate_size + object_size, but that isn't the case.
=> Initial implementation with context parameters

src/main/scala/eu/neverblink/jelly/cli/command/rdf/RdfToJelly.scala, src/test/scala/eu/neverblink/jelly/cli/command/rdf/RdfToJellySpec.scala
Closes #118 
I considered making it an error, with a flag to turn it off, but I think a warning is enough.
=> Add a warning for unsupported logical / physical combinations

build.sbt, src/test/scala/eu/neverblink/jelly/cli/command/helpers/RdfAdapter.scala
=> Update Jelly-JVM to 3.4.0

.scala-steward.conf, README.md
Also ignore updates to Jena, as they are impossible to apply right now.
I added a full explanation here: https://github.com/Jelly-RDF/cli/issues/180
=> Add note about RDF 1.2 support status

install.sh
Modifies the installation script to download gzipped files and decompress them locally. Tested on Windows WSL and on Linux via Google Colab, looks as expected
Additionally corrected one tiny detail in the install file. Since the completions install command always asks the user to run `eval "$(jelly-cli completions install --env)"`, it made no sense to run it in the install.sh regardless. If we would like to completely silence the output from completions install and just do it ourselves, please let me know and I can correct it in a follow-up PR.
=> Move the installation script to use gzipped files

install.sh
Right now, the output of the install script is heavily simplified and completions are installed and added to the current PATH silently. Example of a fresh installation
=> Silence completions

README.md
=> Add installation instructions for mise

build.sbt
Issue #195
Enable the SkipFlow optimization in AoT builds to save on binary size. Details: https://medium.com/graalvm/skipflow-producing-smaller-executables-with-graalvm-f18ca98279c2
This trimmed 2MB from the binary size:
```
$ ls -lh
-rwxrwxr-x 1 piotr piotr  46M Aug 22 21:16 jelly-cli-os
-rwxrwxr-x 1 piotr piotr  44M Aug 24 23:11 jelly-cli-skipflow
```
Throughput baseline:
```
$ time ./jelly-cli-os rdf transcode nanopubs.jelly > /dev/null
real    1m57,221s
user    1m47,978s
sys     0m9,163s
```
Throughput with this change applied:
```
$ time ./jelly-cli-skipflow rdf transcode nanopubs.jelly > /dev/null
real    1m56,017s
user    1m47,645s
sys     0m8,306s
```
So, no significant difference, but we saved some binary size.
=> AoT builds: enable the SkipFlow optimization

src/main/java/eu/neverblink/jelly/cli/graal/GraalSubstitutes.java
Issue #195
Introduces compile-time substitutions that make it impossible for the program to reach code that is not really used in jelly-cli, but still bloats the binary size.
Notably, this excludes all HTTP and SSL code used by JSON-LD context resolvers (we don't have to support that...) and Jena SPARQL (this is not used at all). We also trim out unused cyphers, which were included due to Jena using UUIDs for blank nodes.
This reduces the binary size by a further 10MB:
```
$ ls -lh
-rwxrwxr-x 1 piotr piotr  44M Aug 24 23:11 jelly-cli-skipflow
-rwxrwxr-x 1 piotr piotr  34M Aug 24 23:42 jelly-cli-skipflow-substitutes
```
Baseline throughput:
```
$ time ./jelly-cli-skipflow rdf transcode nanopubs.jelly > /dev/null
real    1m56,017s
user    1m47,645s
sys     0m8,306s
```
With this change …
=> AoT optimization: trim out unused code

.github/workflows/aot-test.yml, .github/workflows/scala.yml, build.sbt, src/main/scala/eu/neverblink/jelly/cli/command/Version.scala, src/main/scala/eu/neverblink/jelly/cli/command/rdf/RdfFromJelly.scala, src/main/scala/eu/neverblink/jelly/cli/command/rdf/RdfToJelly.scala, src/main/scala/eu/neverblink/jelly/cli/command/rdf/RdfValidate.scala, src/main/scala/eu/neverblink/jelly/cli/command/rdf/util/RdfPerformanceOptions.scala, src/main/scala/eu/neverblink/jelly/cli/graal/JenaInternalsFeature.scala, src/main/scala/eu/neverblink/jelly/cli/util/jena/JenaSystemOptions.scala, src/main/scala/eu/neverblink/jelly/cli/util/jena/riot/FastParserProfile.scala, src/main/scala/eu/neverblink/jelly/cli/util/jena/riot/RiotParserUtil.scala, src/test-serial/scala/eu/neverblink/jelly/cli/command/rdf/TermValidationSpec.scala, src/test/scala/eu/neverblink/jelly/cli/command/VersionSpec.scala, src/test/scala/eu/neverblink/jelly/cli/command/helpers/TestFixtureHelper.scala, src/test/scala/eu/neverblink/jelly/cli/command/rdf/RdfFromJellySpec.scala, src/test/scala/eu/neverblink/jelly/cli/command/rdf/RdfToJellySpec.scala, src/test/scala/eu/neverblink/jelly/cli/command/rdf/RdfValidateSpec.scala
Closes #196
Validating IRIs and literals can take up even ~30–40% of runtime in `rdf to-jelly`. Most of the time we don't need that at all, because we only care about converting between formats, and not the validity of IRI schemas, or whether 30th February is a real date or not.
This disables validation by default in `to-jelly` and `from-jelly` commands, with the largest benefit being in the second case. Jelly by itself already bypasses some of these validations.
Lazy mapping of literals into value space should be fine, but we can't easily enable that from outside of Jena. I wrote a small routine using reflection to fix that. It may fail if reflection is not supported – e.g., if the JVM doesn't support it, or when Graal is misconfigured. We detect that and ignore it – the program will …
=> Disable Jena IRI/literal validation by default

build.sbt, src/main/scala/eu/neverblink/jelly/cli/command/Version.scala, src/test/scala/eu/neverblink/jelly/cli/command/VersionSpec.scala
Add info about creator, license, and add a link to the repo.
=> --version: add copyright information

README.md
I was wrong, this is not how mise works. This doesn't help at all. You have to upgrade manually.
=> README: remove misguided mise option

src/main/scala/eu/neverblink/jelly/cli/ErrorHandler.scala, src/test/scala/eu/neverblink/jelly/cli/command/ErrorHandlerSpec.scala
While debugging #217 I noticed that unknown errors are reported by default with a rather unhelpful message:
```
$ jelly-cli rdf to-jelly test.xml 
Unknown error
Run with --debug to see the complete stack trace.
```
It would make sense to always print the long stack trace for unknown errors, as otherwise, there is no way to see what happened. Hiding exception details makes sense only for known errors, for which we have helpful user messages.
I changed the ErrorHandler behavior to fix that.
=> Print stack trace for all unknown errors

.github/workflows/aot-test.yml, build.sbt
Closes #217
Surprisingly, there is no appreciable difference in the binary size. I'm not complaining!
=> Fix reporting XML parse errors in AoT builds

src/main/scala/eu/neverblink/jelly/cli/command/rdf/RdfToJelly.scala, src/main/scala/eu/neverblink/jelly/cli/command/rdf/RdfValidate.scala, src/main/scala/eu/neverblink/jelly/cli/command/rdf/util/RdfFormat.scala, src/main/scala/eu/neverblink/jelly/cli/command/rdf/util/RdfPerformanceOptions.scala, src/main/scala/eu/neverblink/jelly/cli/util/jena/JenaSystemOptions.scala, src/main/scala/eu/neverblink/jelly/cli/util/jena/riot/RiotParserUtil.scala, src/test/scala/eu/neverblink/jelly/cli/command/rdf/RdfToJellySpec.scala
Previously we lumped together IRI resolution with literal validation in the `--validate-terms` option, which is not great. For formats like TTL, JSON-LD and RDF/XML supporting BASE resolution is pretty much mandatory so as not to lose information specified in the file, and we were not doing that by default.
This introduces a new option, enabled by default for formats that support BASE, to resolve IRIs properly.
I've also despaghettified the validate-terms option a bit.
This will make parsing of RDF/XML, JSON-LD, and Turtle a bit slower by default, but you can restore previous performance with `--resolve-iris=false`.
=> Fix BASE resolution for formats that support it
